### PR TITLE
Backtosearch 498

### PR DESCRIPTION
**Pull request by wgilling**
Pull this feature branch down and clear the cache. The only changes are a minor addition to the theme code and a corresponding twig file to render the link.

The theme now has a asulib_barrio_preprocess_region method that only sets the link if:
1. region name is "sidebar_first"
2. current route is "entity.node.canonical"
3. the referer_url ($_SERVER["HTTP_REFERER"]) value contain "/search"

To test this, navigate to any search results and click on randomly selected items; it also holds true that the search may be filtered before selecting an item -- so that "search" should persist as what the user returns to. Also, do the same from a collection search page.

_NOTE: this code could be adjusted to display the same link above subsequent search pages for example clicking on a facet or a taxonomy "Linked agent" link that is actually another search page, but that seemed like it could get confusing for the user - by removing the logical condition that the route = "entity.node.canonical"._

### CODE REVIEW

**Comment by elizoller** [comment]
my local is not seeing this theme file even after multiple cache clears - is it being read from in yours?

**Comment by elizoller** [comment]
is this what i should see?
Screen Shot 2021-10-29 at 12 17 28 PM

**Comment by wgilling** [comment]
> is this what i should see? 

yeah -- we did not really decide how it should be styled, but I feel that we should potentially use a "back" font awesome glyph.

**Comment by wgilling** [comment]
NEED to add logic to limit this link display for referer pages that also contain the base site domain such as keep.lib.asu.edu.

**Comment by wgilling** [comment]
I added a commit that will use the superglobal $_SERVER['SERVER_NAME'] value instead of loading the site config since it should be just as reliable. This string value would be 'keep.lib.asu.edu' or 'prism.lip.asu.edu' or 'localhost' and the logic merely requires that the $referer_url contains this string as well as the "/search" string match.

To test, this is kinda tricky to test cases where the URL comes from a remote server location where that url contains "/search" but the domain is not OUR domain... perhaps it is simple enough to look at the code and conclude that it would not appear in those cases.

**Pull request merged**
