### PR TITLE
Ready to merge

### PR DESCRIPTION
**Pull request by wgilling**
Adjusted order of stats boxes, made the items box into a link, and use bootstrap classes for the 3-by cell layout for #161... only changed the block code and a tiny bit of the module CSS.

### CODE REVIEW

**Comment by wgilling** [comment]
I don't think this will close the related issue : https://github.com/asulibraries/islandora-repo/issues/161

**Comment by elizoller** [comment]
why not?

**Comment by wgilling** [comment]
there was a button on the issue or branch itself to "Make Pull request and close", but I entered the pull request by just clicking a "Make pull request" link. No worries -- just if you could please close the related ticket when this is merged.

**Comment by elizoller** [comment]
ok will do

**Pull request merged**
