### PR TITLE
Asu collection extras

### PR DESCRIPTION
**Pull request by wgilling**
_cannot automatically merge it? lol .... you love doing challenging merges like I like to have hairs pulled out one at a time._

One future enhancement will do an inner loop to get the same stats for each nodes' complex object child nodes.

### CODE REVIEW

**Comment by elizoller** [comment]
its just because we both added islandora_matomo in core.extension.yml
thats an easy one :D

**Comment by wgilling** [comment]
> its just because we both added islandora_matomo in core.extension.yml
> thats an easy one :D

phew -- nice and easy.

There are a couple extra blocks in this module still -- we may want to wait for me to clean it up. It's up to you.

**Comment by elizoller** [comment]
no worries, i'll wait

**Comment by wgilling** [comment]
code updated to make adjustments to collection search view, exposed block, and twig - also renamed the asu_collection_extras in the info file for #111 and #55... this should all be merged while crossing your fingers. I really think that I didn't miss anything, but it is a possibility.

**Pull request merged**
