### PR TITLE
Nosearch breadcrumb 497

### PR DESCRIPTION
**Pull request by wgilling**
Pull down this branch and clear the caches.

To confirm the breadcrumb, navigate to the search page without search terms at both: http://localhost:8000/search?search_api_fulltext= and http://localhost:8000/search. See that the breadcrumb reads either "KEEP / Search" or "PRISM / Search" based on which site you're configured for.

### CODE REVIEW

**Comment by elizoller** [comment]
i think the logic for the breadcrumb is too general - ie it shows up on the share your work form and the `/collections` view

Screen Shot 2021-10-28 at 12 40 25 PM

**Comment by wgilling** [comment]
Ok -- adjusted the logic in the theme preprocess code so that it checks the current route :

```
index bc7fced4..fa212475 100644
--- a/web/themes/custom/asulib_barrio/asulib_barrio.theme
+++ b/web/themes/custom/asulib_barrio/asulib_barrio.theme
@@ -73,7 +73,7 @@ function asulib_barrio_preprocess_breadcrumb(&$variables) {
           'attributes' => new Attribute(['class' => ['is_active']])
         ];
       }
-      else {
+      elseif ($current_route == "view.solr_search_content.page_1" || $curent_route == "view.solr_search_content.page_3") {
         $variables['breadcrumb'][] = [
           'text' => 'Search',
           'attributes' => new Attribute(['class' => ['is_active']])

```

**Comment by elizoller** [comment]
does that work you on a collection search page like `http://localhost:8000/collections/57/search?search_api_fulltext=` ? 
it works now on the main site search (`page_1`) but not on `page_3`?

**Comment by wgilling** [comment]
the variable name was wrong!! I had a type `$curent_route`.

**Pull request merged**
