### PR TITLE
Ws2 homepage recent stuff

### PR DESCRIPTION
**Pull request by wgilling**
This branch adjusts the twig and view output for the homepage Recent Items / Collections & Featured Collections as well as includes some css to adjust the look. This also adds a new thumbnail image style so that a single hook can add the CSS class to it in the theme code.

The following views will need to be imported:

- config/sync/image.style.card_image.yml 
- config/sync/views.view.collections.yml 
- config/sync/views.view.content_recent.yml 
- config/sync/views.view.display_media.yml 
- config/sync/views.view.featured_collections.yml 

The issues that this branch addresses :
Homepage - KEEP: Recent items/recent collections: change layout to horizontal (but this was decided to use card-header-icon instead of card-horizontal), no title links or buttons on any of these cards, drop description from Recent collection, use card-hover (and stretched-link)
Homepage - PRISM: recent items 4x1 using thumbnails and card + card-hover, the Featured collections uses a card-horizontal and card-hover as well. So, no title links or buttons on any of these cards.

In order to test PRISM or KEEP, I just edit the Site name value on http://localhost:8000/admin/config/system/site-information

### CODE REVIEW

**Comment by elizoller** [comment]
has jordyn looked all of this?

**Comment by elizoller** [comment]
why wouldn't we use thumbnails anymore?

**Comment by wgilling** [comment]
we had a brief meeting and decided that the PRISM homepage display of Recent Items was way too large due to the image thumbnails being in there at all and decided to go with glyphs for all items so they are all the same small size and switch the card style to `card-header-icon` but I am not sure if we do 2x2 or 1x4 since the 1x4 allows them to each have their own width (a CSS change would be needed to make it the page content width).

**Comment by wgilling** [comment]
> why wouldn't we use thumbnails anymore?

the look was bad when there were mixtures of thumbnails and glyphs. This did have a padding under the card header before the text that could be removed and even used the wrong title H5 wrappers - supposed to be H3 by brand standards.
Screen Shot 2021-08-19 at 8 50 38 AM

Compare to:
Screen Shot 2021-08-19 at 8 52 12 AM

**Comment by wgilling** [comment]
We had a meeting with Jordyn and decided some things. All of those changes to this branch have been done including:

- removed description from all Recent Collections / Featured Collection displays
- replaced all images with glyphs and changed card style to card-header-icon as well as adjusted spacing between rows of items for KEEP for Recent Items & Recent Collections

This should be able to be merged with `develop` and it contains an Image style that is needed by the `ws2_collection_browse` branch.

**Comment by wgilling** [comment]
current version of this looks like:
Screen Shot 2021-08-26 at 10 26 45 AM

Screen Shot 2021-08-26 at 9 26 54 AM

**Pull request merged**
