### PR TITLE
Complex object search

### PR DESCRIPTION
**Pull request by wgilling**
This should be ready to review and merge. The added display to handle the search has been added to the collection search view (due to the vast number of similarities it has with the collection search).

To review, install and import the config files:

- config/sync/block.block.exposedformsolr_search_contentpage_2.yml
- config/sync/views.view.collections.yml 
- config/sync/views.view.solr_search_content.yml 
- config/sync/block*
- config/sync/facets*

Clear the views cache and navigate to a complex object that has at least two children that have some searchable metadata (for search feasibility). Try the link and search form that appear in the "Explore this item" sidebar block.

### CODE REVIEW

**Comment by wgilling** [comment]
Search page filter language “Explore this item” and the “explore all” link in sidebar block (performs an empty search in the object)
We should change this to “Explore media”
Change “Explore this item” to “Explore {complex object title}” on the search results page

**Comment by wgilling** [comment]
Need to trim the title of the complex object before wrapping with [Explore "TITLE"].

Need to add the facets.

**Comment by wgilling** [comment]
Ok -- now it's ready to review on a different VM and merge.

There was a little bug that was fixed after adding the complex object search facets and corresponding blocks - that the exposed form alter code was not getting a node and that error prevented any blocks from rendering.

Also, a tiny change to the complex object search results landing page title calculation... the paragraphs that make up the title were trimmed before wrapping in **Explore "COMPLEX_TITLE"** to get rid of any data error spaces that were left over.

**Comment by elizoller** [comment]
functionally this PR is ready to go
we just need clarification on the language of items vs media

**Comment by wgilling** [comment]
updated the language for the "Explore this collection" block according to the latest design meeting.

I had to merge in `develop` because my newer VM was not cooperating with anything until I did (both the solr collection and complex object searches had no results).

READY to review and merge.

**Pull request merged**
